spring.application.name=consumer-service
server.port=8081

ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
ollama.embedding.model=nomic-embed-text

qdrant.host=${QDRANT_HOST:localhost}
qdrant.port=${QDRANT_PORT:6334}

spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=excel-group
spring.kafka.consumer.auto-offset-reset=earliest

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}
